Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,9 +33,10 @@ jobs:
       - run:
           name: Build and push Docker image
           command: |
-            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-            docker build -t $DOCKERHUB_USERNAME/make-quiz-service:latest .
-            docker push $DOCKERHUB_USERNAME/make-quiz-service:latest
+            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && echo "Docker login succeeded" || echo "Docker login failed"
+            docker build -t $DOCKERHUB_USERNAME/make-quiz-service:latest . && echo "Docker build succeeded" || echo "Docker build failed"
+            docker push $DOCKERHUB_USERNAME/make-quiz-service:latest && echo "Docker push succeeded" || echo "Docker push failed"
+            
 workflows:
   build-and-test:
     jobs:
